# for module compiling
import os
Import('remove_components')
from building import *

objs = []
cwd  = GetCurrentDir()
list = os.listdir(cwd)


for item in list:
    if item in remove_components:
        continue

    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        objs = objs + SConscript(os.path.join(item, 'SConscript'))

# join the emWin/Demo for building script
objs = objs + SConscript( GetCurrentDir() + '/emWin/Demo/SConscript', variant_dir = 'build/emWin/Demo', duplicate = 0)				
Return('objs')
