Import('RTT_ROOT')
Import('rtconfig')
from building import *

#cwd     = GetCurrentDir()

# The set of source files associated with this SConscript file.
src = Split("""
Config/GUIConf.c
Config/GUIDRV_Template.c
Config/LCDConf_FlexColor_Template.c
OS/GUI_X_OS.c
Lib/STemWin528_CM4_OS_Keil.lib
Lib/STemWin528_CM4_OS_Keil_ot.lib
""")

#CPPPATH = [cwd]
# The set of source files associated with this SConscript file.
path = [RTT_ROOT + '/components/emWin', RTT_ROOT + '/components/emWin/inc']

CPPDEFINES = []


group = DefineGroup('emWin', src, depend = ['RT_USING_EMWIN'], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
