# for module compiling
import os
Import('RTT_ROOT')

cwd = str(Dir('#'))
objs = []
#cwd  = GetCurrentDir()
list = os.listdir(cwd)

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

# join the CMSIS/DSP_Lib for building script
objs = objs + SConscript( cwd + '/Libraries/CMSIS/DSP_Lib/SConscript', variant_dir = 'build', duplicate = 0)				

Return('objs')
